name: "Sphinx Docs Check"
on:
  push:
    paths:
    - 'docs/**'
    - 'ldcoolp_figshare/**'
    - '.github/workflows/sphinx*yml'
  pull_request:
    paths:
    - 'docs/**'
    - 'ldcoolp_figshare/**'
    - '.github/workflows/sphinx*yml'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ldcoolp-figshare
      uses: actions/checkout@v4
    - name: Sphinx build
      uses: ammaraskar/sphinx-action@8.2.3
      with:
        docs-folder: "docs/"
